### ISSUE TITLE
Hello , i have a question about the problem 'Rotten Uploader'

### ISSUE THREAD

**Issue by mutepigz** [73696e65/ctf-notes#1]
how do you get the secret file 'F<'..?
how do you get the source of 'file_list.php'?
thanx..

**Comment by 73696e65** [comment]
Hello, I think you should wait for a better writeup :-) It was just a guess and I don't think I have an intended solution. 

When I have checked special characters for the download script, I realised that < and > are doing something strange, so both

```
curl "rup.chal.ctf.westerns.tokyo/download.php?f=test.>"
curl "rup.chal.ctf.westerns.tokyo/download.php?f=test.<"
```

gave you the `test.c` source code. Then I just guessed the first character of the file, `F` or `f` and that's all.
