### ISSUE TITLE
How do you know str1 and str2?

### ISSUE THREAD

**Issue by daoduythuan** [73696e65/ctf-notes#3]
I don't know how you can have str1 and str2
`str1 = "\x33\x2b\x79\x49\x26\x2a\x76\x2f\x2e\x2b\x73\x49\x24\x36\x6a\x2b\x38\x49\x78\x25\x2d\x22\x12\x21\x29\x30\x12\x30\x2e\x2a"`
`str2 = "\x61\x68\x4a\x64\x14\x1a\x47\x19\x03\x72\x36\x08\x6c\x1b\x2e\x6a\x6c\x1a\x55\x67\x68\x76\x46\x64\x7b\x1d\x50\x7f\x67\x63"`
Can you explain? 
Thank you.

**Comment by 73696e65** [comment]
I already answered you here: https://github.com/73696e65/ctf-notes/issues/2
